export const akaStub = () => [
  {
    titleId: "tt4154796",
    ordering: 1,
    title: "Avengers: Endgame",
    region: null,
    language: null,
    types: "original",
    attributes: null,
    isOriginalTitle: true,
  },
  {
    titleId: "tt4154796",
    ordering: 2,
    title: "Avengers: Endgame",
    region: "AE",
    language: null,
    types: "imdbDisplay",
    attributes: null,
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154796",
    ordering: 3,
    title: "Avengers: Endgame",
    region: "AR",
    language: null,
    types: "imdbDisplay",
    attributes: null,
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154796",
    ordering: 4,
    title: "Avengers: Phase finale",
    region: "CA",
    language: "fr",
    types: "imdbDisplay",
    attributes: null,
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154796",
    ordering: 5,
    title: "Мстители: Финал",
    region: "KZ",
    language: "ru",
    types: "imdbDisplay",
    attributes: null,
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154756",
    ordering: 1,
    title: "Avengers: Infinity War",
    region: null,
    language: null,
    types: "original",
    attributes: null,
    isOriginalTitle: true,
  },
  {
    titleId: "tt4154756",
    ordering: 2,
    title: "Avengers: Infinity War",
    region: "AL",
    language: null,
    types: "imdbDisplay",
    attributes: null,
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154756",
    ordering: 3,
    title: "Avengers: Infinity War",
    region: "AR",
    language: null,
    types: "imdbDisplay",
    attributes: null,
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154756",
    ordering: 4,
    title: "Avengers: Infinity War",
    region: "UY",
    language: null,
    types: null,
    attributes: "short title",
    isOriginalTitle: false,
  },
  {
    titleId: "tt4154756",
    ordering: 5,
    title: "Avengers: Cuộc Chiến Vô Cực",
    region: "VN",
    language: null,
    types: "imdbDisplay",
    attributes: "translated title",
    isOriginalTitle: false,
  },
];
