import { BasicsModel } from "src/basics/schema/basics.schema";

export const basicStub = () => [
  {
    tconst: "tt0000022",
    titleType: "short",
    primaryTitle: "Blacksmith Scene",
    originalTitle: "Les forgerons",
    isAdult: false,
    startYear: 1895,
    endYear: null,
    runtimeMinutes: 1,
    genres: ["documentary", "short"],
  },
  {
    tconst: "tt0067098",
    titleType: "tvEpisode",
    primaryTitle: "Willi Forst",
    originalTitle: "Willi Forst",
    isAdult: false,
    startYear: null,
    endYear: null,
    runtimeMinutes: 55,
    genres: [],
  },
  {
    tconst: "tt0108778",
    titleType: "tvSeries",
    primaryTitle: "Friends",
    originalTitle: "Friends",
    isAdult: false,
    startYear: 1994,
    endYear: 2004,
    runtimeMinutes: 22,
    genres: ["comedy", "romance"],
  },
  {
    tconst: "tt34808440",
    titleType: "movie",
    primaryTitle: "Between Friends",
    originalTitle: "Between Friends",
    isAdult: false,
    startYear: 2024,
    endYear: null,
    runtimeMinutes: 90,
    genres: ["thriller"],
  },
  {
    tconst: "tt1349010",
    titleType: "video",
    primaryTitle: "Oil Overload 2",
    originalTitle: "Oil Overload 2",
    isAdult: true,
    startYear: 2008,
    endYear: null,
    runtimeMinutes: null,
    genres: ["adult"],
  },
  {
    tconst: "tt1481346",
    titleType: "video",
    primaryTitle: "Big Butt Oil Orgy",
    originalTitle: "Big Butt Oil Orgy",
    isAdult: true,
    startYear: 2009,
    endYear: null,
    runtimeMinutes: null,
    genres: ["adult"],
  },
  {
    tconst: "tt34740878",
    titleType: "movie",
    primaryTitle: "Taghiev: Oil",
    originalTitle: "Taghiev: Oil",
    isAdult: false,
    startYear: 2024,
    endYear: null,
    runtimeMinutes: 120,
    genres: ["biography", "history"],
  },
  {
    tconst: "tt19843414",
    titleType: "short",
    primaryTitle: "Oil Oil Oil",
    originalTitle: "Oil Oil Oil",
    isAdult: false,
    startYear: 2023,
    endYear: null,
    runtimeMinutes: 24,
    genres: ["short"],
  },
  {
    tconst: "tt5592584",
    titleType: "short",
    primaryTitle: "Avenge Myself",
    originalTitle: "Avenge Myself",
    isAdult: false,
    startYear: 2016,
    endYear: null,
    runtimeMinutes: 6,
    genres: ["short", "action"],
  },
  {
    tconst: "tt0083602",
    titleType: "movie",
    primaryTitle: "The Avenging",
    originalTitle: "The Avenging",
    isAdult: false,
    startYear: 1982,
    endYear: null,
    runtimeMinutes: 50,
    genres: ["western"],
  },
  {
    tconst: "tt4154796",
    titleType: "movie",
    primaryTitle: "Avengers: Endgame",
    originalTitle: "Avengers: Endgame",
    isAdult: false,
    startYear: 2019,
    endYear: null,
    runtimeMinutes: 181,
    genres: ["sci-fi", "adventure", "action"],
  },
  {
    tconst: "tt16103750",
    titleType: "movie",
    primaryTitle: "Rifftrax: Avengers: Endgame",
    originalTitle: "Avengers: Endgame",
    isAdult: false,
    startYear: 2020,
    endYear: null,
    runtimeMinutes: null,
    genres: ["sci-fi", "comedy", "action"],
  },
  {
    tconst: "tt4154756",
    titleType: "movie",
    primaryTitle: "Avengers: Infinity War",
    originalTitle: "Avengers: Infinity War",
    isAdult: false,
    startYear: 2018,
    endYear: null,
    runtimeMinutes: 149,
    genres: ["sci-fi", "adventure", "action"],
  },
];
